name       : libxklavier
version    : 5.4
release    : 7
source     :
    - http://pkgs.fedoraproject.org/repo/pkgs/libxklavier/libxklavier-5.4.tar.bz2/13af74dcb6011ecedf1e3ed122bd31fa/libxklavier-5.4.tar.bz2 : 17a34194df5cbcd3b7bfd0f561d95d1f723aa1c87fca56bc2c209514460a9320
homepage   : http://freedesktop.org/wiki/Software/LibXklavier
license    :
    - LGPL-2.0
summary    : The libxklavier package contains a utility library for X keyboard.
builddeps  :
    - pkgconfig(xkbfile)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(xkeyboard-config)
rundeps    :
    - xkeyboard-config
component  : desktop.core
description: |
    The libxklavier package contains a utility library for X keyboard.
setup      : |
    %configure --disable-static \
               --with-xkb-bin-base=/usr/bin \
               --with-xkb-base=/usr/share/X11/xkb
build      : |
    %make
install    : |
    %make_install
