name        : libxklavier
version     : 5.3
release     : 6
source      :
    - http://ftp.gnome.org/pub/gnome/sources/libxklavier/5.3/libxklavier-5.3.tar.xz : ebec3bc54b5652838502b96223152fb1cd8fcb14ace5cb02d718fc3276bbd404
homepage    : http://freedesktop.org/wiki/Software/LibXklavier
license     :
    - LGPL-2.0
summary     : The libxklavier package contains a utility library for X keyboard.
builddeps   :
    - pkgconfig(x11)
    - pkgconfig(xkeyboard-config)
rundeps     :
    - xkeyboard-config
description : |
    The libxklavier package contains a utility library for X keyboard.
setup      : |
    %configure --disable-static \
               --with-xkb-bin-base=/usr/bin \
               --with-xkb-base=/usr/share/X11/xkb
build      : |
    %make
install    : |
    %make_install
